modLoader="javafml"
loaderVersion="[40,)"
license="Apache Public License v2"
[[mods]]
modId="dynmap_ftbessentials"
version="${file.jarVersion}"
displayName="Dynmap-FTBEssentials"
#logoFile="examplemod.png"
credits=""
authors="mikeprimm"
description='''
Dynmap extension for showing warp from the FTB-Essentials
'''
[[dependencies.dynmap_ftbessentials]] 
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="SERVER"
[[dependencies.dynmap_ftbessentials]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="SERVER"
[[dependencies.dynmap_ftbessentials]] 
    modId="dynmap"
    mandatory=true
    versionRange="[3.4,)"
    ordering="NONE"
    side="SERVER"
[[dependencies.dynmap_ftbessentials]] 
    modId="ftbessentials"
    mandatory=true
    versionRange="[1802.1,)"
    ordering="NONE"
    side="SERVER"
